# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-02 05:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0002_auto_20171202_1110'),
    ]

    operations = [
        migrations.RenameField(
            model_name='restaurants',
            old_name='Date',
            new_name='date',
        ),
    ]
